### ISSUE TITLE
Django 5.x support

### ISSUE THREAD

**Issue by eirnym** [pixeldomain/django-datetime-utc#5]
Could you please verify if the module still works with Django 5.x as well. The field code itself is compatible with Django 1.x based on info in setup.py and there. no information and no tests if this is actually compatible with Django 5.x

To say if this module has support for many versions of Django as listed, I prefer to have integration tests with each major Django update (it's not only major versions) with Sqlite and PostgreSQL to actually show, that it's compatible.

I see test with an installed version of Django, but I'd like to have a matrix test with various versions.

**Comment by pixeldomain** [comment]
Yes I can confirm this still works in Django 5.x. Compatibility is listed as >= Django 1.5.

**Comment by eirnym** [comment]
so I should not expect explicit tests for many Django versions for this component?

**Comment by pixeldomain** [comment]
I don't plan to add any more tests as I don't actively work on this project. I update it after each major Django release if required. If you would like to add more tests yourself you are welcome to submit a PR.

**Comment by eirnym** [comment]
You don't need to write test cases. For that you need to introduce tool like tox and a GitHub workflow

**Comment by pixeldomain** [comment]
> You don't need to write test cases. For that you need to introduce tool like tox and a GitHub workflow

@eirnym I finally got around to looking at this. A GitHub workflow now exists, it runs the tests against all the actively supported Django versions. Thanks for the suggestion.
